GRANT REPLICATION SLAVE ON *.* TO 'ro_mysql_user'@'%';
GRANT REPLICATION CLIENT ON *.* TO 'ro_mysql_user'@'%';
GRANT SELECT ON *.* TO 'ro_mysql_user'@'%';
GRANT REPLICATION_SLAVE_ADMIN, GROUP_REPLICATION_ADMIN, BINLOG_ADMIN ON *.* TO 'ro_mysql_user'@'%';
FLUSH PRIVILEGES;

CHANGE REPLICATION SOURCE TO
SOURCE_HOST ='master_mysql',
SOURCE_PORT=3306,
SOURCE_USER='wo_mysql_user',
SOURCE_PASSWORD='wo_pass',
SOURCE_AUTO_POSITION = 1;

START REPLICA;