version: '3.9'

services:
  write_only_db:
    image: mysql:latest
    container_name: master_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${WO_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${WO_MYSQL_USER}
      MYSQL_PASSWORD: ${WO_MYSQL_PASSWORD}
    ports: 
      - "3306:3306"
    volumes:
      - volume_wo_mysql:/var/lib/mysql
      - ./db-master/etc/mysql/master.conf:/etc/my.cnf
      - ./db-master/docker/init_master.sql:/docker-entrypoint-initdb.d/initialize.sql

  read_only_db:
    image: mysql:latest
    container_name: slave_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${RO_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${RO_MYSQL_USER}
      MYSQL_PASSWORD: ${RO_MYSQL_PASSWORD}
    ports: 
      - "3307:3306"
    volumes:
      - volume_ro_mysql:/var/lib/mysql
      - ./db-slave/etc/mysql/slave.conf:/etc/my.cnf
      - ./db-slave/docker/init_slave.sql:/docker-entrypoint-initdb.d/initialize.sql

volumes:
  volume_wo_mysql:
    name: WOV
  volume_ro_mysql:
    name: ROV